- hosts: build_host
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: ./demo-dockerfile
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: ./demo-dockerfile/Dockerfile
        owner: root
        group: root
        mode: '0644'
    - name: copy War file
      copy:
        src: ./QueryFormApplication-0.0.1-SNAPSHOT.war
        dest: ./demo-dockerfile/QueryFormApplication-0.0.1-SNAPSHOT.war
        owner: root
        group: root
        mode: '0644'
    - name: build container image
      docker_image:
        name: webapp-container
        build:
          path: ./demo-dockerfile
          source: build
        state: present
