- hosts: docker_hosts
  gather_facts: no
  tasks:
    - name: copy tarball to host
      copy:
        src: ./webapp-container.tar
        dest: webapp-container.tar

    - name: load container from tarball
      docker_image:
        name: webapp-container
        load_path: webapp-container.tar
        state: present
        source: load
