- hosts: build_host
  gather_facts: no
  tasks:
    - name: archive container image as a tarball
      docker_image:
        name: webapp-container
        archive_path: ./demo-dockerfile/webapp-container.tar
        source: pull
        state: present
